Repository NVIDIA/dgx-cloud-examples, pull requests merged in 2025-09, with the labels that each got.

#11 Lepton templates
  CONTRIBUTING.md
  img/template-launcher.png
  lepton/templates/README.md
  lepton/templates/nccl-mpi-template.sh
  lepton/templates/pytorch-benchmark.py
  lepton/templates/torch-launch.sh
Labels: enhancement

#14 Add contributing guide for Starter Kits
  lepton/starterkits/CONTRIBUTING.md
Labels: starter-kits

#13 Minor clarification of fragment placement
  lepton/templates/README.md
Labels: documentation
